### ISSUE TITLE
Crash with HeightFieldShape

### ISSUE THREAD

**Issue by galvesribeiro** [amerkoleci/JoltPhysicsSharp#90]
Hello!

At our initial test I was trying to create a `HeightFieldShape` to represent our terrain but after initialize the `PhysicsSystem` and start creating the objects the process just crash. No logs, no errors, just exit.

The sample core to reproduce after the `PhysicsSystem` initialization is like this:

```
 int width = 513;
            int length = 513;
            Vector3 positionTest = new Vector3(-25.5f, 0.099f, -25.1f);
            var samples = new float[width * length];
            var heightFieldSettings = new HeightFieldShapeSettings(samples, positionTest, new Vector3(100f, 1f, 100f));

            var heightFieldShape = new HeightFieldShape(heightFieldSettings);
            var settingsTest = new BodyCreationSettings(heightFieldShape, positionTest, Quaternion.Identity, MotionType.Static,
                Layers.NonMoving);
```

The code actually crashes with this call on the constructor which calls `JPH_HeightFieldShapeSettings_Create`:

<img width="997" alt="image" src="https://github.com/user-attachments/assets/9203ba63-6e8d-403a-af72-2734a47d138c">

Any idea what that may be?

Thanks!

**Comment by amerkoleci** [comment]
Hi,
There was an issue in the native call, please update to `2.9.2` and it should be fixed.

Thanks

**Comment by galvesribeiro** [comment]
Thanks for the quick update.

I've updated to 2.9.2 but the same problem still happen. 

It crashes immediately when run that line:

<img width="764" alt="image" src="https://github.com/user-attachments/assets/1f63f8e7-10e7-46d7-9710-056bf544aacd">

**Comment by amerkoleci** [comment]
You need to pass the width as sampleCount not samples.Length

**Comment by galvesribeiro** [comment]
Good catch. It worked. 

Is that kind of error/crashes reported anywhere? I've set  both the TraceHandler and the AssertFailure handlers but they weren't never triggered.

Thanks!

**Comment by amerkoleci** [comment]
It crashed on jolt side: https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Physics/Collision/Shape/HeightFieldShape.cpp#L89

So jump there and ask the author to improve the error maybe?

**Comment by galvesribeiro** [comment]
Cool thanks!
